include ../extra.mk
include ../buildsys.mk

SUBDIRS = \
	alis \
	auth \
	backend \
	botserv \
	chanfix \
	chanserv \
	crypto \
	exttarget \
	gameserv \
	global \
	groupserv \
	helpserv \
	hostserv \
	infoserv \
	memoserv \
	misc \
	nickserv \
	operserv \
	protocol \
	saslserv \
	scripting \
	transport \
	$(CONTRIB_ENABLE)
