SUBDIRS = \
	alis \
	auth \
	backend \
	botserv \
	chanfix \
	chanserv \
	$(SUBMODULE_CONTRIB) \
	crypto \
	exttarget \
	gameserv \
	global \
	groupserv \
	helpserv \
	hostserv \
	infoserv \
	memoserv \
	misc \
	nickserv \
	operserv \
	protocol \
	proxyscan \
	rpgserv \
	saslserv \
	security \
	statserv \
	scripting \
	transport

include ../extra.mk
include ../buildsys.mk
