SUBDIRS =			\
	alis			\
	auth			\
	backend			\
	botserv			\
	chanfix			\
	chanserv		\
	$(CONTRIB_ENABLE)	\
	crypto			\
	exttarget		\
	gameserv		\
	global			\
	groupserv		\
	helpserv		\
	hostserv		\
	infoserv		\
	memoserv		\
	misc			\
	nickserv		\
	operserv		\
	protocol		\
	proxyscan		\
	rpgserv			\
	saslserv		\
	scripting		\
	security		\
	statserv		\
	transport

include ../extra.mk
include ../buildsys.mk
