# Copyright (c) 2003-2004 E. Will et al.
# Rights to this code are documented in doc/LICENSE.
#
# This file contains build instructions.
#
# $Id: Makefile.in 8375 2007-06-03 20:03:26Z pippijn $
#

MODULE = protocol

include ../../extra.mk
include ../../buildsys.mk
include ../../buildsys.module.mk

SRCS = \
	asuka.c	\
	bahamut.c	\
	bircd.c	\
	charybdis.c	\
	dreamforge.c	\
	hybrid.c	\
	inspircd-aux.c	\
	inspircd12.c	\
        ircd-seven.c  \
	ircnet.c	\
	ithildin.c	\
	mixin_nohalfops.c	\
	mixin_noholdnick.c	\
	mixin_noowner.c	\
	mixin_noprotect.c	\
	nefarious.c	\
	p10-generic.c	\
	plexus.c	\
	ptlink.c	\
	ratbox.c	\
	shadowircd.c	\
	solidircd.c	\
	ts6-generic.c	\
	undernet.c	\
	unreal.c

CPPFLAGS	+= -I../../include
