# SPDX-License-Identifier: CC0-1.0
# SPDX-URL: https://spdx.org/licenses/CC0-1.0.html
#
# Copyright (C) 2019-2020 Aaron M. D. Jones <me@aaronmdjones.net>

include ../../../extra.mk

includesubdir = atheme/digest

INCLUDES =                  \
    direct.h                \
    gcrypt.h                \
    internal.h              \
    mbedtls.h               \
    openssl.h               \
    types.h

include ../../../buildsys.mk
