# SPDX-License-Identifier: CC0-1.0
# SPDX-URL: https://spdx.org/licenses/CC0-1.0.html
#
# Copyright (C) 2019-2020 Aaron M. D. Jones <aaronmdjones@gmail.com>

include ../../../extra.mk

includesubdir = atheme/digest

INCLUDES =                  \
    constants.h             \
    internal.h              \
    mbedtls.h               \
    openssl.h

include ../../../buildsys.mk
