# Copyright (c) 2003-2004 E. Will et al.
# Rights to this code are documented in doc/LICENSE.
#
# This file contains build instructions.
#
#

MODULE = announceserv

include ../../extra.mk
include ../../buildsys.mk
include ../../buildsys.module.mk

LIBS +=	-L../../libathemecore -lathemecore
SRCS = main.c

CPPFLAGS	+= -I../../include
