# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2010 Stephen Bennett <spb@exherbo.org>
# Copyright (C) 2012 William Pitcock <nenolod@dereferenced.org>
# Copyright (C) 2018-2020 Aaron M. D. Jones <me@aaronmdjones.net>

include ../../extra.mk

MODULE  = scripting
SUBDIRS = ${PERL_COND_D}

include ../../buildsys.mk
