# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2003-2004 E. Will, et al.

MODULE		= scripting
SUBDIRS		= $(PERL_COND_D)

include ../../extra.mk
include ../../buildsys.mk
