include ../../extra.mk

INCLUDES = \
	asuka.h		\
	bahamut.h	\
	charybdis.h	\
	dreamforge.h	\
	hybrid.h	\
	inspircd.h	\
	ircd-seven.h	\
	ircnet.h	\
	nefarious.h	\
	officeirc.h	\
	ratbox.h	\
	shadowircd.h	\
	sporksircd.h	\
	ultimate3.h	\
	undernet.h	\
	unreal.h

includesubdir = $(PACKAGE)/protocol

include ../../buildsys.mk
