# Copyright (c) 2003-2004 E. Will et al.
# Rights to this code are documented in doc/LICENSE.
#
# This file contains build instructions.
#
# $Id: Makefile.in 8375 2007-06-03 20:03:26Z pippijn $
#

MODULE = operserv

include ../../extra.mk
include ../../buildsys.mk
include ../../buildsys.module.mk

SRCS = \
	main.c	\
	akill.c	\
	clearchan.c	\
	clones.c	\
	compare.c	\
	greplog.c	\
	help.c	\
	identify.c	\
	ignore.c	\
	info.c	\
	inject.c	\
	jupe.c	\
	mode.c	\
	modinspect.c	\
	modlist.c	\
	modload.c	\
	modreload.c	\
	modunload.c	\
	noop.c	\
	override.c	\
	raw.c		\
	rakill.c	\
	readonly.c	\
	rmatch.c	\
	rehash.c	\
	restart.c	\
	rnc.c		\
	rwatch.c	\
	shutdown.c	\
	sgline.c	\
	soper.c	\
	specs.c	\
	sqline.c	\
	uptime.c	\
	update.c

CPPFLAGS	+= -I../../include
