# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2010 William Pitcock <nenolod@dereferenced.org>
# Copyright (C) 2020 Aaron M. D. Jones <me@aaronmdjones.net>

include ../../extra.mk

PROG_NOINST = createtestdb${PROG_SUFFIX}
SRCS        = createtestdb.c

include ../../buildsys.mk

build: all
