# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2012 William Pitcock <nenolod@dereferenced.org>
# Copyright (C) 2014 Lee Starnes <starnelt@dukes.jmu.edu>
# Copyright (C) 2015-2016 Max Teufel <max@teufelsnetz.com>
# Copyright (C) 2018-2020 Aaron M. D. Jones <me@aaronmdjones.net>

include ../../../extra.mk

includesubdir = atheme/protocol

INCLUDES =                  \
    asuka.h                 \
    bahamut.h               \
    charybdis.h             \
    chatircd.h              \
    elemental-ircd.h        \
    inspircd.h              \
    nefarious.h             \
    ngircd.h                \
    unreal.h

include ../../../buildsys.mk
