include ../../../extra.mk

INCLUDES =			\
	asuka.h			\
	bahamut.h		\
	charybdis.h		\
	elemental-ircd.h	\
	inspircd.h		\
	nefarious.h		\
	unreal.h

includesubdir = $(PACKAGE)/protocol

include ../../../buildsys.mk
