/*
 * Copyright (c) 2005-2010 Atheme Development Group
 * Rights to this code are documented in doc/LICENSE.
 *
 * This file contains version information.
 * Autogenerated by version.sh.
 */

#include "serno.h"

const char *revision = SERNO;

const char *infotext[] =
{
  "Atheme IRC Services --",
  "Copyright (c) 2005-2010 Atheme Development Group (http://www.atheme.org)",
  "Portions copyright (c) 2004 Shrike Developers (http://www.malkier.net)",
  " ",
  "Permission to use, copy, modify, and/or distribute this software for any",
  "purpose with or without fee is hereby granted, provided that the above",
  "copyright notice and this permission notice appear in all copies.",
  " ",
  "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS AS IS AND",
  "ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED",
  "WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE",
  "DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR",
  "ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES",
  "(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;",
  "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON",
  "ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT",
  "(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS",
  "SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
  " ",
  "Currently Atheme's core group consists of the following developers,",
  "in nick-alphabetical order:",
  "  elly, Elly <elly@leptoquark.net>",
  "  jdhore, JD Horelick <jdhore1@gmail.com>",
  "  jilles, Jilles Tjoelker <jilles@stack.nl>",
  "  nenolod, William Pitcock <nenolod@nenolod.net>",
  "  spb, Stephen Bennett <spb@exherbo.org>",
  " ",
  "The following people have contributed blood, sweat and tears to",
  "this Atheme release:",
  "  Adam, Adam <adam@sigterm.info>",
  "  alambert, Alex Lambert <alambert@quickfire.org>",
  "  beu, Elfyn McBratney <elfyn.mcbratney@gmail.com>",
  "  Dianora, Diane Bruce <db@db.net>",
  "  danieldg, Daniel De Graaf <danieldegraaf@gmail.com>",
  "  dKingston, Michael Rodriguez <dkingston@dkingston.net>",
  "  gxti, Michael Tharp <gxti@partiallystapled.com>",
  "  kog, Greg Feigenson <kog@epiphanic.org>",
  "  kuja, Jeff Katz <jeff@katzonline.net>",
  "  lu_zero, Luca Barbato <lu_zero@gentoo.org>",
  "  pfish, Patrick Fish <pofish@gmail.com>",
  "  pippijn, Pippijn van Steenhoven <pippijn@one09.net>",
  "  terminal, Theo Julienne <admin@ozweb.nu>",
  "  tomaw, Tom Wesley <tom@tomaw.net>",
  "  Trystan, Trystan Scott Lee <trystan@nomadirc.net>",
  "  w00t, Robin Burchell <viroteck@viroteck.net>",
  "  zparta, Jens Holmqvist <zparta@hispan.se>",
  " ",
  "Portions of Atheme's code was derived from Shrike, which was mostly developed by",
  "the following developers in nick-alphabetical order:",
  "  madragoran, Mike Campbell <madragoran@avendesora.net>",
  "  nenolod, William Pitcock <nenolod@nenolod.net>",
  "  rakaur, Eric Will <rakaur@malkier.net>",
  "  rintaun, Matt Lanigan <rintaun@projectxero.net>",
  "  sycobuny, Stephen Belcher <sycobuny@malkier.net>",
  " ",
  "Visit our website at http://www.atheme.net",
  0,
};
