# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2012 William Pitcock <nenolod@dereferenced.org>
# Copyright (C) 2012 Jilles Tjoelker <jilles@stack.nl>
# Copyright (C) 2014 Rylai <gando.depth@gmail.com>
# Copyright (C) 2018-2020 Aaron M. D. Jones <me@aaronmdjones.net>

include ../extra.mk

includesubdir = .

INCLUDES = atheme.h
SUBDIRS  = atheme

include ../buildsys.mk
