# SPDX-License-Identifier: ISC
# SPDX-URL: https://spdx.org/licenses/ISC.html
#
# Copyright (C) 2010 William Pitcock <nenolod@dereferenced.org>
# Copyright (C) 2020 Aaron M. D. Jones <aaronmdjones@gmail.com>

include ../../extra.mk

PROG_NOINST = createburst${PROG_SUFFIX}
SRCS        = createburst.c

include ../../buildsys.mk

build: all
